name: Our Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
      - run: ls -al
      - run: cat kustomize/overlays/dev/kustomization.yaml
      - name: change yaml
        run: |
            cat <<EOF> kustomize/overlays/dev/kustomization.yaml 
            images:
              - name: nginx
                newName: nginx
                newTag: 1.23.1
            EOF
      - name: after change
        run: cat kustomize/overlays/dev/kustomization.yaml
      
